### PR TITLE
Fixed icon position

### PR DESCRIPTION
**Pull request by mabar**
Fix for #22

### CODE REVIEW

**Comment by enumag** [comment]
Hmm... I'm afraid this might break older Tracy. Can you check how the official debug bar panels or those in Kdyby handle this? I have a feeling the right solution is different than this.

**Comment by mabar** [comment]
It seems like a bug in tracy css. This extension is the same as others. Except there is missing text.  With text it works well.

```
<span title="Session sections">
    <img src="<?php echo $esc($src(__DIR__ . '/logo.png')); ?>" />
    <span>session</span>
</span>
```

**Comment by enumag** [comment]
I see. In that case maybe a line-height would be better?

**Comment by mabar** [comment]
line-height have no effect. Fixed with zero-width joiner which should not break bc

**Comment by enumag** [comment]
Good, thanks. :-)

**Pull request merged**
